add test mode for rate request
purplship/purplship-node pull request #5
Opened 2021-09-07 15:29 UTC by jayabahu

aadd test mode for rate request

2021-09-07 16:29 UTC, DanH91 requested changes
Hello @jayabahu,

I left a quick note. Thanks for opening up the PR

2021-09-07 16:29 UTC, DanH91 commented on src/generated/api/ProxyApi.js
> +    fetchRates(data, opts, callback) {
Hi @jayabahu,

Thanks for taking the time to submit the PR.
The code located under `src/generated/**` is generated using the https://openapi-generator.tech/

The issue is that I forgot to generate the client for the latest purplship server release `2021.7`

Would you mind using the generator to update the entire `generated/*` folder with the latest purplship OpenAPI specs?

It can be done with a couple of commands

```terminal
mkdir client

docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate \
		-i https://raw.githubusercontent.com/purplship/purplship-server/main/schemas/openapi.json \
		-g javascript \
		-o /local/client \
                --additional-properties=modelPropertyNaming=snake_case


rm -rf purplship-node/src/generated/*
cp -r client/src/* purplship-node/src/generated/
```

Let me know if you can take care of it or let me know I will do it.


Thanks

2021-09-08 06:41 UTC, jayabahu commented on src/generated/api/ProxyApi.js
> +    fetchRates(data, opts, callback) {
@DanH91 

Thanks for quick response and I have updated the code.

2021-09-08 13:03 UTC, DanH91 commented
Hey @jayabahu,

Thank you for the contribution, I will merge this and publish the release.

2021-09-08 13:03 UTC, merged